### ISSUE TITLE
Website 404s

### ISSUE THREAD

**Issue by balupton** [soundblogs/soundplayer-electron#1]
http://labs.voronianski.com/get-soundplayer-osx gives 404 not found

Seems like an awesome app, very well designed!

**Comment by voronianski** [comment]
@balupton it's not ready yet :)

**Comment by balupton** [comment]
No worries, to reduce confusion perhaps remove it from here until it is ready:

![screen shot 2016-03-10 at 1 35 35 am](https://cloud.githubusercontent.com/assets/61148/13644368/70713db2-e660-11e5-9f01-ca1eff122527.png)
